---

- name: Docker
  hosts: grafana
  become: yes
  tasks:

    - name: Uninstall old docker
      apt:
        name:
          - docker.io
          - python3-docker
          - docker-doc
          - docker-compose
          - docker-compose-v2
          - podman-docker
          - containerd
          - runc
        state: absent

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install dependencies via apt
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg

    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker's APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name:
          - python3-docker
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Add user to Docker group
      user:
        name: markin
        append: yes
        groups: docker
        

