---

- name: Elastic
  hosts: elastic
  become: yes
  tasks:
    - name: Install required packages
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - wget
        state: present
        update_cache: yes

    - name: Add the Elasticsearch repository from Yandex mirror
      become: yes
      shell: echo "deb [trusted=yes] https://mirror.yandex.ru/mirrors/elastic/8/ stable main" | tee /etc/apt/sources.list.d/elastic-8.x.list

    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Elasticsearch
      ansible.builtin.apt:
        name: elasticsearch
        state: present

#    - name: Replace elasticsearch.yml
#      template:
#        force: yes
#        src: /home/markin/ansible/configs/elasticsearch.yml
#        dest: /etc/elasticsearch/elasticsearch.yml
        
#    - name: Replace jvm.options
#      template:
#        force: yes
#        src: /home/markin/ansible/configs/jvm.options
#        dest: /etc/elasticsearch/jvm.options

    - name: systemctl daemon-reload
      become: yes
      shell: systemctl daemon-reload

    - name: Ensure Elasticsearch is enabled and started
      ansible.builtin.systemd:
        name: elasticsearch
        enabled: yes
        state: started

