---

- name: Grafana
  hosts: grafana
  become: yes
  tasks:

    - name: Run Grafana container
      docker_container:
        name: grafana01
        image: "grafana/grafana:latest"
        state: started
        ports:
          - "3000:3000"

